Feature/refactoring
jarmovdh/data-table-vng pull request #7
Opened 2022-11-14 13:57 UTC by jarmovdh

2022-11-15 09:20 UTC, RubenWerdmuller commented
Hola 👋 

Hierbij nog de lijst van de review, voor het gemak en in geval van overdragen 🤷‍♂️ 

- Verwijder altijd ongebruikte dingen, ook al heb jij ze er niet in gezet. Is een goede gewoonte. Nu staat bijv. een api pagina die toegankelijk is, maar je eigenlijk niet wil
- Op de home pagina staat een div, kan beter een react fragment zijn
- De styled component Button heeft een fijnere syntax, check hun docs!
- `StyledSelect` is dubbelop
- button-holder is geen top naam. Container en wrapper zijn wat conventioneler
- Je gebruikt op twee plekken index.tsx, tsx bestanden zijn alleen voor bestanden met React bedoeld
- In het table component heb je react buttons in de data. Dat wil je in principe nooit! Dit hoort ook niet in de data thuis, maar zijn gewoon acties vanuit het tabel zelf
- Maak alle datums die je gebruikt in de data ISO 8601, je wilt in de buurt komen van realistische data
in de data staan dingen als active, en account, dat zijn namen die zouden hier niet voor gebruikt worden, wat zijn denk je betere namen
- Je sort function kan heel veel generieker! Dat is iets waar je wat effort in wil stoppen bij functioneel programmeren. Probeer bijv. eens een variabel mee te geven aan de functie
- Op de "sorteer op" zit een `htmlFor=""`. Let op, dat lost misschien wel een error message oid op, maar is geen goede code! dit werkt alleen als je een id op de input mee geeft
- Het filter in de template van de table heeft heel veel logica, verplaats dat filter naar de plek waar je de state set van de sortedTable
- Je gebruikt veel role= dingen, is dat echt nodig?

2022-11-15 11:11 UTC, amijsb requested changes
Paar opmerkingen 🚀

2022-11-15 11:11 UTC, amijsb commented on pages/index.tsx
>        <DataTable></DataTable>
Tags zonder children mogen self-closing zijn.

2022-11-15 11:11 UTC, amijsb commented on src/components/button/Button.tsx
> +  icon: string;
Ik denk dat het nog beter is om de `icon` expliciet te typen, dus de opties mee te geven: `icon: "bin" | "lock" | ...`. Zo weet je altijd precies welke opties er zijn.

2022-11-15 11:11 UTC, amijsb commented on src/components/button/Button.tsx
> +  return <Styled.Button onClick={onClick}>{getIcon()}</Styled.Button>;
Je zou ook ipv een functie in de Button te zetten, de icons in de template kunnen returnen:
```suggestion
 return (
    <Styled.Button onClick={onClick}>
      {icon === "bin" && <BinIcon />}
      {icon === "lock" && <LockCloseIcon />}
      {...}
    </Styled.Button>
  );
```

2022-11-15 11:11 UTC, amijsb commented on fixtures/mockData.tsx
> +});
Ik denk dat je dit in je component wil hebben, niet in de fixtures. In je fixtures wil je echt alleen mock data hebben.

2022-11-15 11:11 UTC, amijsb commented on src/components/table/DataTable.styled.tsx
>  });
Ik zie dat je in deze file overal `camelCase` css properties gebruikt. Hoewel dit wel werkt, is het niet de correcte notatie voor web. Native gebruikt `camelCase`, web gebruikt `kebab-case` als conventie. Ook is het aan te raden om units te gebruiken, bijv. `padding-bottom: 15px;`.

Hier een voorbeeld van de conventionele notering van styled-components:
```
export const Wrapper = styled.div`
  align-items: center;
  display: flex;
  gap: 20px;
  justify-content: flex-end;
  padding-bottom: 15px;

  @media screen and (max-width: 730px) {
    align-items: flex-end;
    display: flex;
    flex-direction: column;
  }
`;
```

2022-11-15 15:18 UTC, RubenWerdmuller commented
@jarmovdh @amijsb Voor het button component wil ik vragen om icons als `children` of als `prop` mee te geven. Bij voorbaad alle mogelijke icons definiëren voor een generiek component is erg restrictief en daarom ook geen goede practice. 

Hoe je een icon als prop mee geeft kun je afkijken bij voorbeeld [Ant Design](https://codepen.io/pen?&editors=001)

2022-11-16 13:32 UTC, RubenWerdmuller requested changes
Steady as she goes. Good busy!

2022-11-16 13:32 UTC, RubenWerdmuller commented on fixtures/mockData.tsx
> +    accesTo: "DEGO DOOK Autobranche",
Try to use arrays when stacking data

```suggestion
    accessTo: [DEGO, DOOK, Autobranche],
```

2022-11-16 13:32 UTC, RubenWerdmuller commented on fixtures/mockData.tsx
> +    setActions: "write",
Actions is plural, but the value is singular

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.styled.tsx
> +  @media screen and (max-width: 730px) {
We usually tend to work mobile-first 😉

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +  const sortKey = sortOptions.map((entry) => entry.label);
Avoid unnecessary component "root" level variables. In this case, this variable isn't needed at all 👋

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +  const buttonIcons = data.map((entry) => entry.setActions);
This abstraction is so small, it might not make the code more readable

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +      console.log(sortKey);
Remove log

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +      const keyB = b[sortKey];
Nice abstraction, but so small it might not be necessary

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +              <MenuItem key={label} value={label} onClick={() => handleSort(label)}>
this has `label` as `value`, seems odd!

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +    handleSort(sortKey as string | any);
`| any` should not be necessary here and is generally only used when there is no time to properly type

2022-11-16 13:32 UTC, RubenWerdmuller commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/components/table/DataTable.jsx"],
`jsx` files React without Typescript. Change the `DataTable.jsx` to `DataTable.tsx` file and remove this config

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +    } else if (
this `else` is not needed if you're returning a value.

```suggestion
    }
```

2022-11-16 13:32 UTC, RubenWerdmuller commented on src/components/table/DataTable.tsx
> +      return value;
The filter method expects a true or false value, so return either true or false

2022-11-16 14:14 UTC, amijsb commented on src/components/table/DataTable.tsx
> +    handleSort(sortKey as string | any);
Do you still need this `useEffect`?

2022-11-16 14:16 UTC, amijsb commented on src/components/table/DataTable.tsx
>            >
Since you now handle your sort based on the clicking of menu items, do you still need this function?

2022-12-08 10:59 UTC, merged